Derive smoothness from `mtb:scale` and `tracktype`
FixMyBerlin/atlas-geo pull request #59
Opened 2023-09-22 09:30 UTC by rush42

This PR implements a mapping from the tags 'mtb:scale` and `tracktype` to derive values for smoothness.
Closes [973](https://github.com/FixMyBerlin/private-issues/issues/973)

2023-09-22 09:32 UTC, rush42 commented
@tordans please check if the mapping I suggested works out for you

2023-09-25 08:43 UTC, tordans requested changes
Some documentation and also small updated on the transformation after comparing streetcomplete's smoothness gallery.

2023-09-25 08:43 UTC, tordans commented on app/process/roads_bikelanes/surfaceQuality/DeriveSmoothness.lua
> +function SmoothnessFromMTBScale(scale)
```suggestion
-- https://wiki.openstreetmap.org/wiki/Key:mtb:scale
-- https://taginfo.openstreetmap.org/keys/mtb%3Ascale#values
function SmoothnessFromMTBScale(scale)
```

2023-09-25 08:43 UTC, tordans commented on app/process/roads_bikelanes/surfaceQuality/DeriveSmoothness.lua
> +  }
```suggestion
  local trackTypeToSmoothness = {
    ["grade1"] = "good",
    ["grade2"] = "intermediate",
    ["grade3"] = "bad",
    ["grade4"] = "bad",
    ["grade5"] = "very_bad"
  }
```

2023-09-25 08:43 UTC, tordans commented on app/process/roads_bikelanes/surfaceQuality/DeriveSmoothness.lua
> +function SmoothnessFromTrackType(type)
```suggestion
-- Wiki https://wiki.openstreetmap.org/wiki/Key:tracktype
-- Categories that cyclosm.org use https://github.com/cyclosm/cyclosm-cartocss-style/wiki/Tag-to-Render
-- Mapping of Smoothness<>Surface https://wiki.openstreetmap.org/wiki/Key:smoothness/Gallery
-- Mapping of Smoothness<>Surface (Legacy) https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/smoothness
function SmoothnessFromTrackType(type)
```

2023-09-25 08:43 UTC, tordans commented on app/process/roads_bikelanes/surfaceQuality/SurfaceQuality.lua
>    -- 2. `smoothess` extrapolated from surface data
```suggestion
  -- 1. `smoothess` tag
  -- 2. `smoothess` extrapolated from `surface` data
  -- 3. `smoothess` extrapolated from `tracktype` tag, mostly on `highway=track`
  -- 4. `smoothess` extrapolated from `mtb:scale` tag, mostly on `highway=path`
```

2023-10-04 09:10 UTC, merged