Add Bicycle Parking Data Set
FixMyBerlin/atlas-geo pull request #70
Opened 2023-11-06 12:32 UTC by rush42

This PR adds two data sets containing entries of bicycle parking infrastructure. One contains point geometries of bicycle parking and the other contains mostly parking areas which are mapped as areas. The point data set also includes the entries of the second data set where the respective point corresponds to the centroid of the mapped area.

Capacity values get processed s.t. the `capacity` tag only contains the number of "normal" bicycle parking spots and not the total parking spots e.g. `capacity = capacity - capacity:cargo_bikes`. Apart from that we copy only the tags described on the [OSM Wiki - Bicycle Parking](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking) page.

[Related Ticket](https://github.com/FixMyBerlin/private-issues/issues/1094)

2023-11-06 13:00 UTC, tordans requested changes
Vielen Dank. Anmerkungen in den Kommentaren.

Weitere random Gedanken…

- Ich muss mal schauen, wo diese 61 relations in DE herkommen https://taginfo.geofabrik.de/europe:germany/tags/amenity=bicycle_parking#overview
- Wir sollten die Tags normalisieren und uns TODOs schreiben, wenn sie nicht rein passen. Sonst kann ich mich in der Translation im Inspector nicht darauf verlassen, was ankommt. Das betrifft bspw. access, bicycle_parking, covered, lit, operator:type, und vermutlich noch ein paar in der Tag Liste. <-- Das kann aber step 2 sein, nachdem wir das was hier ist schonmal in der Karte haben.

2023-11-06 13:00 UTC, tordans commented on app/process/bicycleParking/bicycleParking.lua
> +local tags_cc = {"area", "operator", "covered", "indoor", "foot_traffi", "access", "capacity", "fee","bicycle_parking","cyclestreets_id", "maxstay", "surveillance"}
Bitte als Liste formatieren oder zumindest einheitlich mit Leerzeichen. Am besten Linter auf die Datei anwenden (https://github.com/trixnz/vscode-lua).

```suggestion
-- also https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende/Fahrradparkpl%C3%A4tze
local tags_cc = {"area", "operator", "operator:type", "covered", "indoor", "access", "cargo_bike", "capacity", "capacity:cargo_bike", "fee", "lit", "surface", "bicycle_parking", "mapillary", "maxstay", "surveillance", "bicycle_parking:count", "bicycle_parking:position", "traffic_sign" }
```

2023-11-06 13:00 UTC, tordans commented on app/process/bicycleParking/bicycleParking.lua
> +  local capacities = {capacity = tonumber(tags.capacity) or 0}
Nur sicherheitshalber: Das setzt nicht immer alles auf 0, was eigentlich NULL wäre? Wenn etwas nicht number ist, sollten wir NULL schreiben, weil dann die capacity nicht existiert (also ein TODO ist). "0" wäre ja eine klare Aussage, wenn auch eine sehr ungewöhnliche.

2023-11-06 13:00 UTC, tordans commented on app/process/bicycleParking/bicycleParking.lua
> +    tags = capacityNormalization(tags),
Das ist nur so richtig, oder?

```suggestion
  local tags = capacityNormalization(object.tags)
  CopyTags(object.tags, tags, tags_cc, "osm_")

  nodeTable:insert({
    tags = tags
```

2023-11-06 13:00 UTC, tordans commented on app/process/bicycleParking/bicycleParking.lua
> +  if ExitProcessing(object) or not object.is_closed then return end
Verstehe ich in einer Zeile nicht…

```suggestion
  if not object.is_closed then return end
  if ExitProcessing(object) then return end
```

2023-11-06 13:00 UTC, tordans commented on app/process/bicycleParking/bicycleParking.lua
> +  if ExitProcessing(object) or not object.is_closed then return end
ABER, wir haben noch einen 3. EdgeCase: Fahrradständer, die als Linie gemapped sind.
Dann ist es zwar `….process_way`, aber es ist _nicht_ `…is_closed`. Diese Fälle sollten wir IMO nur als Punkte speichern und die Linie verwerfen.

Leider sieht man in https://taginfo.geofabrik.de/europe:germany/tags/amenity=bicycle_parking#overview nicht, wie viele reine Linien (keine Areas) sind.

2023-11-06 13:01 UTC, tordans commented
Ach, noch etwas, bitte pack noch die fresh-ness Logik mit hier rein.

2023-11-07 09:01 UTC, rush42 commented on app/process/bicycleParking/bicycleParking.lua
> +  local capacities = {capacity = tonumber(tags.capacity) or 0}
Returne nun ein leeres Objekt, falls wir `capacity=nil` haben.

2023-11-07 09:46 UTC, rush42 commented
> Alles klar. Auf `check_date:amenity` oder `check_date:bicycle_parking` ?
Habe gerade einen kurzen Check auf den Berlin-Daten gemacht und keiner der beiden Tags scheint Eintraege zu haben.

2023-11-07 15:04 UTC, merged